name: build
# description:
# - Runs Gradle build compiling source code and executing tests
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/workflows/cancel.yml'
      - '.github/workflows/clear-packages.yml'
      - '.github/workflows/deploy-dev.yml'
      - '.github/workflows/deploy-prod.yml'
      - '.github/workflows/release.yml'
      - '.github/workflows/updater.yml'
      - '.gitignore'
      - 'gradle.properties'
      - 'LICENSE'
      - 'README.md'

jobs:
  build:
    name: Run Build
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Create release' && !contains(github.event.head_commit.message, 'Deploy dev') && !contains(github.event.head_commit.message, 'Deploy prod') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: adopt

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          gradle-version: wrapper

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.0
