name: deploy-dev
# description:
# - Downloads versioned JAR artifact from repository
# - Deploys JAR to Azure App Services in development
on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    name: Run Deploy
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Deploy dev') }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download Release Artifact
        run: |
          package=$(awk '/group/{print $NF; exit}' build.gradle.kts | sed s/\'//g | sed s/\"//g | tr "." "/")
          name=$(awk '/rootProject.name/{print $NF; exit}' settings.gradle.kts | sed s/\'//g | sed s/\"//g)
          version=$(echo "${COMMIT_MESSAGE}" | sed 's/[^0-9.]*\([0-9.]*\).*/\1/')
          file=${name}-${version}.jar
          artifact_uri="https://maven.pkg.github.com/${GITHUB_REPOSITORY}/${package}/${name}/${version}/${file}"

          mkdir -p build/libs
          cd build/libs

          curl -H "Authorization: token ${GITHUB_TOKEN}" -L ${artifact_uri} -o ${file}

        env:
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_DEV }}

      - name: Configure App Settings
        uses: azure/appservice-settings@v1
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_DEV }}
          app-settings-json: ${{ secrets.AZURE_APP_SETTINGS_DEV }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_NAME_DEV }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
          package: build/libs/*.jar
