name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/analyze.yml
      - .github/workflows/cancel.yml
      - .github/workflows/clear-packages.yml
      - .github/workflows/deploy-dev.yml
      - .github/workflows/deploy-prod.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/gradle-app-postgres-build.yml@main
    with:
      java-version: 17
      postgres-admin-db-uri: ${{ vars.POSTGRES_ADMIN_DB_URI }}
      postgres-build-db-uri: ${{ vars.POSTGRES_BUILD_DB_URI }}
      run-coverage: false
      run-fossa: false
      run-gradle-validation: true
    secrets:
      postgres-admin-password: ${{ secrets.POSTGRES_ADMIN_DB_PASSWORD }}
      postgres-build-db-svc-name: ${{ secrets.POSTGRES_BUILD_DB_SVC_NAME }}
      postgres-build-db-svc-password: ${{ secrets.POSTGRES_BUILD_DB_SVC_PASSWORD }}
