name: build

on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-app-postgres-build.yml@main
    with:
      java-version: 17
      postgres-admin-db-uri: ${{ vars.POSTGRES_ADMIN_DB_URI }}
      postgres-build-db-uri: ${{ vars.POSTGRES_BUILD_DB_URI }}
      run-coverage: false
      run-fossa: false
      run-gradle-validation: true
    secrets:
      postgres-admin-password: ${{ secrets.POSTGRES_ADMIN_DB_PASSWORD }}
      postgres-build-db-svc-name: ${{ secrets.POSTGRES_BUILD_DB_SVC_NAME }}
      postgres-build-db-svc-password: ${{ secrets.POSTGRES_BUILD_DB_SVC_PASSWORD }}
