name: deploy-dev

on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - dev

jobs:
  deploy-dev:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-azure-app-service-deploy.yml@main
    with:
      azure-env: dev
      azure-app-name: ${{ vars.AZURE_APP_NAME_DEV }}
      github-maven-package-base-uri: ${{ vars.GH_MAVEN_PACKAGE_BASE_URI }}
    secrets:
      azure-app-credentials: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      azure-app-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
      azure-app-settings: ${{ secrets.AZURE_APP_SETTINGS_DEV }}
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
