name: deploy-dev

on:
  push:
    branches:
      - main

jobs:
  deploy-dev:
    uses: opengoodio/central-workflows/.github/workflows/gradle-azure-app-service-deploy.yml@main
    with:
      env: dev
    secrets:
      azure-app-credentials: ${{ secrets.AZURE_CREDENTIALS_DEV }}
      azure-app-name: ${{ secrets.AZURE_APP_NAME_DEV }}
      azure-app-profile: ${{ secrets.AZURE_APP_SETTINGS_DEV }}
      azure-app-settings: ${{ secrets.AZURE_PUBLISH_PROFILE_DEV }}
