name: release

on:
  pull_request:
    types:
      - closed
      - labeled
    branches:
      - main
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  release:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-github-release.yml@main
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
      java-version: 21
      run-gradle-validation: true
    secrets:
      workflow-token: ${{ secrets.WORKFLOW_TOKEN }}
