name: build

on:
  push:
    branches:
      - '**'
      - '!main'
    paths-ignore:
      - .github/workflows/*
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-app-build.yml@main
    with:
      java-version: 21
      run-coverage: false
      run-gradle-validation: true
