name: build

on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/workflows/cancel.yml
      - .github/workflows/clear-packages.yml
      - .github/workflows/deploy-dev.yml
      - .github/workflows/deploy-prod.yml
      - .github/workflows/release.yml
      - .gitignore
      - gradle.properties
      - LICENSE
      - README.md

jobs:
  build:
    uses: opengoodio/central-workflows/.github/workflows/gradle-app-build.yml@main
    with:
      java-version: 11
      run-coverage: false
      run-fossa: false
      run-gradle-validation: false
