name: deploy-prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    uses: opengoodio/central-workflows/.github/workflows/gradle-azure-app-service-deploy.yml@main
    with:
      env: prod
    secrets:
      azure-app-credentials: ${{ secrets.AZURE_CREDENTIALS_PROD }}
      azure-app-name: ${{ secrets.AZURE_APP_NAME_PROD }}
      azure-app-profile: ${{ secrets.AZURE_PUBLISH_PROFILE_PROD }}
      azure-app-settings: ${{ secrets.AZURE_APP_SETTINGS_PROD }}
