name: release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    uses: opengood-aio/central-workflows/.github/workflows/gradle-github-release.yml@main
    with:
      git-email: ${{ vars.GIT_EMAIL }}
      git-user: ${{ vars.GIT_USER }}
      java-version: 17
      run-gradle-validation: true
