name: gradle-github-release

on:
  workflow_call:
    inputs:
      git-email:
        type: string
        description: Git user email address
        required: true
      git-user:
        type: string
        description: Git user username
        required: true
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 21
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true
    secrets:
      workflow-token:
        description: GitHub workflow secret for pushing automated commits
        required: true

jobs:
  gradle-github-release:
    name: Gradle GitHub Release
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false
          token: ${{ secrets.workflow-token }}

      - name: Setup Git
        run: |
          git config user.email ${GIT_EMAIL}
          git config user.name ${GIT_USER}
          git config url.https://${{ secrets.workflow-token }}@github.com/.insteadOf https://github.com/
        env:
          GIT_EMAIL: ${{ inputs.git-email }}
          GIT_USER: ${{ inputs.git-user }}

      - name: Setup Java
        uses: actions/setup-java@v4.2.2
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0
        with:
          validate-wrappers: ${{ inputs.run-gradle-validation }}

      - name: Release and Publish
        run: ./gradlew clean release -PskipTests=true -Prelease.useAutomaticVersion=true
        env:
          GITHUB_USER: ${{ inputs.git-user }}
          GITHUB_TOKEN: ${{ secrets.workflow-token }}
