name: gradle-app-build

on:
  workflow_call:
    inputs:
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 17
      run-coverage:
        type: boolean
        description: Value indicating if coverage step should run
        required: true
      run-fossa:
        type: boolean
        description: Value indicating if FOSSA step should run
        required: true
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true
    secrets:
      fossa-api-key:
        description: FOSSA licensing scan API key
        required: false

jobs:
  gradle-app-build:
    name: Gradle App Build
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Create release' && !contains(github.event.head_commit.message, 'Deploy') }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        if: ${{ inputs.run-gradle-validation == 'true' }}
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Java
        uses: actions/setup-java@v3.4.1
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          gradle-version: wrapper

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.1

      - name: Coverage
        if: ${{ inputs.run-coverage == 'true' }}
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: FOSSA
        if: ${{ inputs.run-fossa == 'true' }}
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{ secrets.fossa-api-key }}
