name: gradle-app-postgres-build

on:
  workflow_call:
    secrets:
      fossa-api-key:
        description: FOSSA licensing scan API key
        required: false
      postgres-admin-db-uri:
        description: Postgres admin database connection URI
        required: true
      postgres-admin-password:
        description: Postgres admin password
        required: true
      postgres-build-db-uri:
        description: Postgres database connection URI for performing builds
        required: true
      postgres-build-db-svc-name:
        description: Postgres database service account name for performing builds
        required: true
      postgres-build-db-svc-password:
        description: Postgres database service account password for performing builds
        required: true
      run-coverage:
        description: Value indicating if coverage step should run
        required: true
      run-fossa:
        description: Value indicating if FOSSA step should run
        required: true
      run-gradle-validation:
        description: Value indicating if Gradle validation step should run
        required: true

jobs:
  gradle-app-postgres-build:
    name: Gradle App with Postgres Build
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message != 'Create release' && !contains(github.event.head_commit.message, 'Deploy dev') && !contains(github.event.head_commit.message, 'Deploy prod') }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ secrets.postgres-admin-password }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        if: ${{ run-gradle-validation == 'true' }}
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Java
        uses: actions/setup-java@v3.3.0
        with:
          java-version: 11
          distribution: adopt

      - name: Create Postgres Database and Service Account
        run: |
          psql -c "CREATE USER ${POSTGRES_DB_USER} WITH ENCRYPTED PASSWORD '${POSTGRES_DB_PASSWORD}';" ${POSTGRES_DB_URI}
          psql -f migrations/create_database.sql ${POSTGRES_DB_URI}
        env:
          POSTGRES_DB_URI: ${{ secrets.postgres-admin-db-uri }}
          POSTGRES_DB_USER: ${{ secrets.postgres-build-db-svc-name }}
          POSTGRES_DB_PASSWORD: ${{ secrets.postgres-build-db-svc-password }}

      - name: Database Migration
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: flywayMigrate
          gradle-version: wrapper
        env:
          FLYWAY_URL: ${{ secrets.postgres-build-db-uri }}
          FLYWAY_USER: ${{ secrets.postgres-build-db-svc-name }}
          FLYWAY_PASSWORD: ${{ secrets.postgres-build-db-svc-password }}

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean build
          gradle-version: wrapper
        env:
          SPRING_DATASOURCE_URL: ${{ secrets.postgres-build-db-uri }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.postgres-build-db-svc-name }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.postgres-build-db-svc-password }}

      - name: Codestyle
        uses: fabiocapasso93/gha-kotlin-linter@v1.1

      - name: Coverage
        if: ${{ run-coverage == 'true' }}
        uses: codecov/codecov-action@v3.1.0
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true

      - name: FOSSA
        if: ${{ run-fossa == 'true' }}
        uses: fossas/fossa-action@v1.3.1
        with:
          api-key: ${{ secrets.fossa-api-key }}
