name: gradle-plugin-release

on:
  workflow_call:
    inputs:
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true
    secrets:
      git-email:
        description: Git user email address
        required: true
      git-user:
        description: Git user username
        required: true
      gradle-publish-key:
        description: Gradle plugin key used for publishing to Gradle plugin repository
        required: true
      gradle-publish-secret:
        description: Gradle plugin secret used for publishing to Gradle plugin repository
        required: true

jobs:
  gradle-plugin-release:
    name: Gradle Plugin Release
    runs-on: ubuntu-latest
    if: ${{ github.event.head_commit.message == 'Create release' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate Gradle Wrapper
        if: ${{ inputs.run-gradle-validation == 'true' }}
        uses: gradle/wrapper-validation-action@v1.0.4

      - name: Setup Git
        run: |
          git config user.email ${GIT_EMAIL}
          git config user.name ${GIT_USER}
        env:
          GIT_EMAIL: ${{ secrets.git-user }}
          GIT_USER: ${{ secrets.git-email }}

      - name: Setup Java
        uses: actions/setup-java@v3.4.0
        with:
          java-version: 11
          distribution: adopt

      - name: Release and Publish
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean release -PskipTests=true -Prelease.useAutomaticVersion=true
          gradle-version: wrapper
        env:
          GRADLE_PUBLISH_KEY: ${{ secrets.gradle-publish-key }}
          GRADLE_PUBLISH_SECRET: ${{ secrets.gradle-publish-secret }}
