name: gradle-app-build

on:
  workflow_call:
    inputs:
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 21
      run-coverage:
        type: boolean
        description: Value indicating if coverage step should run
        required: true
      run-gradle-validation:
        type: boolean
        description: Value indicating if Gradle validation step should run
        required: true
    secrets:
      codecov-token:
        description: Codecov code coverage token
        required: false

jobs:
  gradle-app-build:
    name: Gradle App Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Java
        uses: actions/setup-java@v4.5.0
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.2.1
        with:
          validate-wrappers: ${{ inputs.run-gradle-validation }}

      - name: Build
        run: ./gradlew clean build

      - name: Codestyle
        uses: musichin/ktlint-check@v3.0.1
        with:
          ktlint-version: 1.2.1

      - name: Coverage
        if: ${{ inputs.run-coverage == 'true' }}
        uses: codecov/codecov-action@v5.0.7
        with:
          file: ./build/reports/jacoco/test/jacocoTestReport.xml
          verbose: true
          token: ${{ secrets.codecov-token }}
