name: gradle-dependencies-submit

on:
  workflow_call:
    inputs:
      java-distribution:
        type: string
        description: Name of Java JDK distribution to use
        required: false
        default: temurin
      java-version:
        type: number
        description: Version of Java JDK to use
        required: false
        default: 21

jobs:
  gradle-dependencies-submit:
    name: Gradle Dependencies Submit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
      - name: Setup Java
        uses: actions/setup-java@v5.0.0
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Gradle Dependencies Submission
        uses: gradle/actions/dependency-submission@v4.4.3
