name: local-update-actions

on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  local-update-actions:
    name: Workflow Update Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update Workflow Action Versions
        uses: saadmk11/github-actions-version-updater@v0.9.0
        with:
          committer_email: ${{ vars.GIT_EMAIL }}
          committer_username: ${{ vars.GIT_USER }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ignore: '["github/codeql-action/init@v3", "github/codeql-action/autobuild@v3", "github/codeql-action/analyze@v3"]'
