name: python-package-build

on:
  workflow_call:
    inputs:
      python-version:
        type: number
        description: Version of Python to use
        required: false
        default: 3.13
    secrets:
      codecov-token:
        description: Codecov code coverage token
        required: false

jobs:
  python-package-build:
    name: Python Package Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test
        run: |
          pip install pytest pytest-cov
          python -m pytest tests/ --doctest-modules --junitxml=pytest/test-results.xml --cov=com --cov-report=xml --cov-report=html

      - name: Install Ruff
        run: pipx install ruff

      - name: Lint
        run: ruff check --output-format=github --target-version=py313

      - name: Codestyle
        run: ruff format --diff --target-version=py313
        continue-on-error: false

      - name: Coverage
        uses: codecov/codecov-action@v5.4.0
        with:
          files: pytest/test-results.xml
          verbose: true
          token: ${{ secrets.codecov-token }}

      - name: Upload Coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: pytest/
