name: python-package-build

on:
  workflow_call:
    inputs:
      python-version:
        type: number
        description: Version of Python to use
        required: false
        default: 3.13
      run-code-coverage:
        type: boolean
        description: Value indicating if code coverage step should run
        required: true
    secrets:
      codecov-token:
        description: Codecov code coverage token
        required: false

jobs:
  python-package-build:
    name: Python Package Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build
        run: |
          pip install pytest pytest-cov
          python -m pytest --cov-config=pyproject.toml

      - name: Install Ruff
        run: pipx install ruff

      - name: Lint
        run: ruff check --output-format=github --target-version=py313

      - name: Codestyle
        run: ruff format --diff --target-version=py313
        continue-on-error: false

      - name: Coverage
        if: ${{ inputs.run-code-coverage == true }}
        uses: codecov/codecov-action@v5.5.1
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.codecov-token }}
