name: python-py-pi-release

on:
  workflow_call:
    inputs:
      git-email:
        type: string
        description: Git user email address
        required: true
      git-user:
        type: string
        description: Git user username
        required: true
      python-version:
        type: number
        description: Version of Python to use
        required: false
        default: 3.13
      bump-part:
        type: string
        description: Part of semantic version number to bump
        required: false
        default: minor
      run-code-coverage:
        type: boolean
        description: Value indicating if code coverage step should run
        required: true
    secrets:
      codecov-token:
        description: Codecov code coverage token
        required: true
      py-pi-token:
        description: Py PI token for publishing Python packages to Python Package Index
        required: true
      workflow-token:
        description: GitHub workflow token for pushing automated commits
        required: true

jobs:
  python-py-pi-release:
    name: Python PyPI Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    if: ${{ contains(github.event.pull_request.labels.*.name, 'release') && github.event.pull_request.merged == true }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          persist-credentials: false
          token: ${{ secrets.workflow-token }}

      - name: Setup Git
        run: |
          git config user.email ${GIT_EMAIL}
          git config user.name ${GIT_USER}
          git config url.https://$GITHUB_TOKEN@github.com/.insteadOf https://github.com/
        env:
          GIT_EMAIL: ${{ inputs.git-email }}
          GIT_USER: ${{ inputs.git-user }}
          GITHUB_TOKEN: ${{ secrets.workflow-token }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: 'pip'

      - name: Display Python Version
        run: python -c "import sys; print(sys.version)"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Build
        run: pip install build --user

      - name: Set Release Version and Tag
        uses: callowayproject/bump-my-version@master
        env:
          BUMPVERSION_TAG: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ${{ inputs.bump-part }}
          github-token: ${{ secrets.workflow-token }}

      - name: Validate Release Version
        if: ${{ steps.bump.outputs.bumped == true }}
        run: |
          echo "Dev version bumped from ${{ steps.bump.outputs.previous-version }} to release version ${{ steps.bump.outputs.current-version }}!"

      - name: Get Release Version
        run: echo "RELEASE_VERSION=${{ steps.bump.outputs.current-version }}" >> $GITHUB_ENV

      - name: Build Binary Wheel and Source Tarball
        run: python -m build

      - name: Upload Distribution Packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Download Distribution Packages
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

      - name: Sign Distribution Packages
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: >-
            ./dist/*.tar.gz
            ./dist/*.whl

      - name: Publish Distribution Package
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.py-pi-token }}

      - name: Upload Artifact Signatures to GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.workflow-token }}
        run: >-
          gh release upload
          "$GITHUB_REF_NAME" dist/**
          --repo "$GITHUB_REPOSITORY"

      - name: Create GitHub Release
        env:
          RELEASE_NOTES: ${{ github.event.pull_request.body }}
          GITHUB_TOKEN: ${{ secrets.workflow-token }}
        run: >-
          CLEAN_RELEASE_NOTES=$(echo RELEASE_NOTES | sed 's/["'\''`]/ /g')
          echo "CLEAN_RELEASE_NOTES=CLEAN_RELEASE_NOTES" >> $GITHUB_ENV
          gh release create
          "$RELEASE_VERSION"
          --repo "$GITHUB_REPOSITORY"
          --title "$GITHUB_REF_NAME"
          --notes "$CLEAN_RELEASE_NOTES"

      - name: Download Coverage
        if: ${{ inputs.run-code-coverage == 'true' }}
        uses: actions/download-artifact@v4
        with:
          name: coverage
          path: ./coverage.xml

      - name: Coverage
        if: ${{ inputs.run-code-coverage == 'true' }}
        uses: codecov/codecov-action@v5.4.0
        with:
          files: ./coverage.xml
          verbose: true
          token: ${{ secrets.codecov-token }}
