name: workflow-update-actions

on:
  workflow_dispatch:
  schedule:
    # Automatically run every Sunday at midnight
    - cron: '0 0 * * 0'

jobs:
  workflow-update-actions:
    name: Workflow Update Actions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Update Workflow Action Versions
        uses: saadmk11/github-actions-version-updater@v0.7.1
        with:
          committer_username: ${{ secrets.GIT_USER }}
          committer_email: ${{ secrets.GIT_EMAIL }}
          token: ${{ secrets.WORKFLOW_TOKEN }}
          ignore: '["actions/checkout@v2", "actions/cache@v2"]'