name: workflow-clear-packages

on:
  workflow_call:

jobs:
  workflow-clear-packages:
    name: Workflow Clear Packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set Package Name
        run: |
          group=$(awk '/group/{print $NF; exit}' build.gradle.kts | sed s/\'//g | sed s/\"//g)
          name=$(awk '/rootProject.name/{print $NF; exit}' settings.gradle.kts | sed s/\'//g | sed s/\"//g)
          echo "PACKAGE_NAME=${group}.${name}" >> $GITHUB_ENV

      - uses: actions/delete-package-versions@v5.0.0
        with:
          package-name: ${{ env.PACKAGE_NAME }}
          package-type: maven
          min-versions-to-keep: 2
